name: hyphenatorx 
description: Implementation of an hyphenation algorithm, based on TeX definitions.
version: 1.1.1
repository: https://github.com/xErik/hyphenatorx
issues: https://github.com/xErik/hyphenatorx/issues

environment:
  sdk: '>=2.19.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  path: ^1.8.3

flutter:
  assets:
    - assets/
