name: hyphenatorx 
description: Implementation of an hyphenation algorithm for various languages, based on TeX definitions.
version: 1.5.10
repository: https://github.com/xErik/hyphenatorx
issue_tracker: https://github.com/xErik/hyphenatorx/issues

environment:
  # sdk: '>=2.19.6 <4.0.0'
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  path: ^1.8.3

flutter:
  assets:
    - assets/

  fonts:
    - family: roboto
      fonts:
        - asset: test/Roboto-Regular.ttf