name: hyphenatorx 
description: Implementation of an hyphenation algorithm.
version: 1.0.0
homepage: https://github.com/xErik/hyphenatorx

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  assets:
    - assets/
